services:
  node:
    image: ethereum/client-go:v1.13.5
    ports:
      - 8545:8545
    command: [ "--miner.gaslimit", "12000000", "--http", "--http.api", "personal,eth,net,web3,debug", "--http.vhosts", "*,localhost,host.docker.internal", "--http.addr", "0.0.0.0", "--allow-insecure-unlock", "--rpc.allow-unprotected-txs", "--dev", "--verbosity", "2", "--nodiscover", "--maxpeers", "0", "--mine", "--networkid", "1337" ]

  bundler:
    build:
      context: .
      dockerfile: Dockerfile.bundler
    ports:
      - 3000:3000
    command: [ "yarn", "run", "bundler", "--network", "http://node:8545" ]
    depends_on:
      - node
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: relayer
      POSTGRES_PASSWORD: relayer_password
      POSTGRES_DB: relayer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dir:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U relayer" ]
      interval: 5s
      timeout: 5s
      retries: 5

  smtp:
    build:
      context: .
      dockerfile: Dockerfile.smtp
    environment:
      - SERVER_HOST=${SMTP_INTERNAL_SERVER_HOST}
      - SERVER_PORT=${SMTP_INTERNAL_SERVER_PORT}
      - SMTP_DOMAIN_NAME=${SMTP_DOMAIN_NAME}
      - SMTP_LOGIN_ID=${SMTP_LOGIN_ID}
      - SMTP_LOGIN_PASSWORD=${SMTP_LOGIN_PASSWORD}
      - MESSAGE_ID_DOMAIN=${SMTP_MESSAGE_ID_DOMAIN}
      - JSON_LOGGER=${SMPT_JSON_LOGGER}
    ports:
      - "${SMTP_PORT}:${SMTP_INTERNAL_SERVER_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${SMTP_INTERNAL_SERVER_PORT}/api/ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  imap:
    build:
      context: .
      dockerfile: Dockerfile.imap
    environment:
      - RELAYER_ENDPOINT=http://relayer:4500/api/receiveEmail
      - IMAP_LOGIN_ID=${IMAP_LOGIN_ID}
      - IMAP_LOGIN_PASSWORD=${IMAP_LOGIN_PASSWORD}
      - IMAP_DOMAIN_NAME=${IMAP_DOMAIN_NAME}
      - IMAP_PORT=${IMAP_PORT}
      - AUTH_TYPE=${IMAP_AUTH_TYPE}
      - JSON_LOGGER=${IMAP_JSON_LOGGER}

  relayer:
    build:
      context: .
      dockerfile: Dockerfile.relayer
    ports:
      - 4500:4500
    depends_on:
      - db

volumes:
  postgres_data_dir:
